### ISSUE TITLE
Chat is discarding message? Support for large message is desired.

### ISSUE THREAD

**Issue by JG-Adams** [jmont-dev/ollama-hpp#18]
Look what happen in this example:
{"keep_alive":"5m","messages":[{"content":"What are nimbus clouds?","role":"user"},{"content":"Nimbus clouds are dense, moisture-filled clouds that produce rain.","role":"assistant"},{"content":"What are some other kinds of clouds?","role":"user"}],"model":"llama3.1:latest","options":{"seed":42,"top_k":20},"stream":true}

content appears before role.

If you look at the example they gave us from the API documentation it should look like this.
messages := []api.Message{
		api.Message{
			Role:    "system",
			Content: "Provide very brief, concise responses",
		},
		api.Message{
			Role:    "user",
			Content: "Name some unusual animals",
		},
		api.Message{
			Role:    "assistant",
			Content: "Monotreme, platypus, echidna",
		},
		api.Message{
			Role:    "user",
			Content: "which of these is the most dangerous?",
		},
	}

I have tried to provide system prompt as message1 followed by message2 being user, then 3 for assistant, then 4 for user.
It behave unexpectedly as if the 1 message is user and the second is system?

It is for this reason, that I suspect having it in proper order is important.
However, looking at the code, I can't seem to understand how it gets backward or how to get it right.
Please fix this.

**Comment by JG-Adams** [comment]
Earlier I made a pull request to support system for both Generate and Chat. #17
But, then I remove it from Chat because it's supposed to already let you do that.
Now that I discovered it fail to do it, I tried putting it back in my space and it actually work. So for now I would use that.

**Comment by jmont-dev** [comment]
Previously, Ollama required you to set the System parameter in the Modelfile itself. They've added the ability to override it in the API through the new field in the `generate` endpoint and the ability to include it as a message type in `chat`.

There's no issue with `content` appearing before `role` in the first example. This is still valid JSON, and JSON provides no guarantees about the ordering of the key/value pairs that it provides. When Ollama receives the request it will parse out those fields as a dictionary, so the order of individual key/value pairs should not matter.

What definitely does matter is the message order though. These should (and need to) be received in order so that the model can accurately understand the conversation history. It looks like that's happening based on the debug request as the conversation messages themselves occur in the proper order. That should be all that's required for Ollama to interpret them correctly.

I'll do some tests with the system parameter using chat messages and see if I observe any invalid results. In the meantime, I've done some refactoring to allow the user to manually create requests to be sent to the generate, chat, and embedding endpoints. This should allow you to more easily access custom fields such as `system` while I work on getting them included in the base functions. See the new section in the Readme labeled Manual Requests and the example test cases at the end of `test.cpp`:

```C++
// Manually specify all fields
ollama::request request(ollama::message_type::generation);
request["model"]="mistral";
request["prompt"]="Why is the sky blue?";
request["stream"] = false;
request["system"] = "Talk like a pirate for the next reply."
std::cout << ollama::generate(request) << std::endl;
```
Or alternatively:
```C++
// Use the default constructor for generate requests, and add custom fields.
ollama::request request("mistral", "Why is the sky blue?");
request["system"] = "Talk like a pirate for the next reply."
std::cout << ollama::generate(request) << std::endl;
```

**Comment by JG-Adams** [comment]
I see! Thank you for doing this.

**Comment by JG-Adams** [comment]
I tried using chat again with this new method. system is working.
But, I'm getting an issue where it act like I didn't give it any information at all and just hallucinate stuff instead.
It appears to happen when the first message as user is too big?
I might have to guess that it's not designed to take much.

Is there a proper way to inform the AI about something like a worldbuilding for instance?
Also, I'm getting random crashes from using any AI generating options. Even if it's not streamed. I can't tell what cause it.
But, I want to find a way to replicate it by using options.
And so, in trying to use options I'm confused by it because it crash.

Please provide an example on how to use options.

Here's how I tried to use it.
ollama::message message1("user", context);
ollama::message message2("assistant", "I'll remember everything you just gave me.");
ollama::message message3("user", prompt);
ollama::messages messages = {message1, message2, message3};
ollama::request request(ollama::message_type::chat);
request["model"]=Select_AIModel;
request["system"] = system;
request["messages"] = messages.to_json();
//request["options"] = options;
if (options!=nullptr) request["options"] = options["options"];
request["stream"] = false;

Also, putting system before messages still would have it at the end. Why is that?

**Comment by jmont-dev** [comment]
I think the issue is that the `chat` endpoint has no direct `system` parameter; it has be added as a message in the conversation. Only the `generate` endpoint has a system parameter in the Ollama API: https://github.com/ollama/ollama/blob/main/docs/api.md. Passing a system JSON tag directly will work for generate but will likely produce undefined behavior for chat.

The manual requests are designed to allow for setting fields directly, but you should check the API to make sure they're supported for that endpoint otherwise it may produce unexpected results.

I'll investigate why adding a message for system isn't working in chat if you're having issues with that. It should just require adding a message like: `ollama::message message1("system", "Speak like a pirate for the next message");`

**Comment by JG-Adams** [comment]
Ah. That actually fixes the problem then!
That is odd though, with chat I was having problem with it being in message.
I don't know why this exactly. But, for now this manual way to generate response appears to be much better.

Anyway, how do you put in options for manual? I tried figuring it out.

**Comment by JG-Adams** [comment]
Hmm. I tried using a WebUI interface and tested a large prompt. It sees the beginning of something as right in the middle? This is awfully short span of memory. I'm using llama3.1 8b isn't it supposed to have a large context window? How do I use it???

**Comment by JG-Adams** [comment]
I do this.
if (options.contains("options")){
     std::cout << options["options"].dump() << "\n";
}

And yet, in spite of it passing the test, there is an object called options it gives me an error saying it's out of range, not found. and crashes.

**Comment by jmont-dev** [comment]
If you wants to manually add options to a request you can do the following:

```C++
    ollama::options options;
    options["num_ctx"] = 8192;

    ollama::request request(ollama::message_type::generation);
    request["model"] = "llama3.1:8b";
    request["prompt"] = "Why is the sky blue?";
    request["stream"] = false;
    request["options"] = options["options"];

    ollama::response response = ollama::generate(request);
    std::cout << response << std::endl;
```

**Comment by JG-Adams** [comment]
I figured out why it crashes. It's because of the lifetime when using thread. No problem there anymore.

However, I set the option and then do exactly what you did in getting "options" and it ends up empty.
Running your code I gets this.
{"model":"llama3.1:latest","options":{},"prompt":"Why is the sky blue?","stream":false}

options is not supposed to be empty?

So I tried dumping the whole thing to see what it look like.

std::cout << options["options"] << "\n";
std::cout << options.dump() << "\n";
Output:
{}
{"options":{"num_ctx":4096,"num_predict":18,"options":{},"seed":42,"temperature":0,"top_k":20}}

It's not empty. But, it's not getting anything either.

**Comment by jmont-dev** [comment]
I see what you're referring to. That syntax works with the standard constructor for request but isn't working in your example. I'll take a look later.

In the meantime, you can set the options directly as JSON. They're just a dictionary under options:

```C++
    ollama::request request(ollama::message_type::generation);
    request["model"] = "llama3.1:8b";
    request["prompt"] = "Why is the sky blue?";
    request["stream"] = false;
    request["options"]["num_ctx"] = 8192;

    ollama::response response = ollama::generate(request);
    std::cout << response << std::endl;
```

**Comment by JG-Adams** [comment]
Thank you very much! I didn't know you could do that with JSON. I have a lot to learn.
And this actually fix the issue I had with chat not having the full message through!
Chat was discarding messages from first to last when there's more than 2048 words without warning, which made it very confusing.

Tell you what, this is a lot of information we just covered that isn't explained well enough in their API documentation. Maybe you could provide some clarification for this as part of the example.cpp? I mean really, I didn't expect the context window to be capped at all.

I'm liking this manual request format we got here. Very flexible, easy and clean.

I think that with the knowledge like this, we can close this.
